- hosts: all
  remote_user: vagrant
  become: yes
  tasks:

  - name: Instalar python3-pip y git
    apt: name={{ item }} state=installed update_cache=true
    with_items:
        - git
        - python3-pip

  - name: Clonar repositorio
    git: repo=https://github.com/antonioJ95/ProyectoIV.git dest=ProyectoIV/

  - name: Instalar los requisitos del proyecto
    command: pip3 install -r ProyectoIV/requirements.txt